/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InformationSystem;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Ruth
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        try {
            Connection();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    //Connection Method
    Connection con;
    //SQL Statement
    Statement st;
    //SQL Prepared Statement
    PreparedStatement pst;
    
    
    private static final String DbName = "information_systemdb";
    private static final String DbDriver = "com.mysql.cj.jdbc.Driver";
    private static final String DbUrl = "jdbc:mysql://localhost:3306/"+DbName;
    private static final String DbUsername = "root";
    private static final String DbPassword = "@ruthmysql06";
    
    public void Connection() throws SQLException{
        try {
            Class.forName(DbDriver);
            con = DriverManager.getConnection(DbUrl, DbUsername, DbPassword);
            st = con.createStatement();
            
            if (con != null) {
                System.out.println("Connection Successful");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logUsername = new javax.swing.JTextField();
        logPassword = new javax.swing.JPasswordField();
        logLogin = new javax.swing.JButton();
        logEye_Invisible = new javax.swing.JLabel();
        logEye_Visible = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 550));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        jPanel2.add(logLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 450, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Novaliches, Quezon City");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 450, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("3rd Floor, St. Claire Bldg., General Luis,  ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 450, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("WELCOME");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon8-user-30.png"))); // NOI18N
        jLabel2.setText("Username");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon8-password-30.png"))); // NOI18N
        jLabel3.setText("Password");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        logUsername.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        logUsername.setText("Enter Username");
        logUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logUsernameActionPerformed(evt);
            }
        });
        jPanel3.add(logUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 260, -1));

        logPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        logPassword.setText("Enter Password");
        logPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                logPasswordKeyPressed(evt);
            }
        });
        jPanel3.add(logPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 260, -1));

        logLogin.setBackground(new java.awt.Color(255, 51, 0));
        logLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        logLogin.setForeground(new java.awt.Color(255, 255, 255));
        logLogin.setText("Login");
        logLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logLoginActionPerformed(evt);
            }
        });
        jPanel3.add(logLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 90, -1));

        logEye_Invisible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/invieye.png"))); // NOI18N
        logEye_Invisible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logEye_InvisibleMouseClicked(evt);
            }
        });
        jPanel3.add(logEye_Invisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        logEye_Visible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/visieye.png"))); // NOI18N
        logEye_Visible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logEye_VisibleMouseClicked(evt);
            }
        });
        jPanel3.add(logEye_Visible, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 450, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logUsernameActionPerformed

    private void logLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logLoginActionPerformed
        // TODO add your handling code here:
        String username, password;
        username = logUsername.getText();
        password = new String (logPassword.getPassword());
        
        String queryLogin = "Select * FROM accdetails WHERE BINARY accUsername = ? AND accPassword = ? ";

        try {
            pst = con.prepareStatement(queryLogin);
            pst.setString(1, username);
            pst.setString(2, password);
            ResultSet rs = pst.executeQuery();
            if(!rs.next()){
                JOptionPane.showMessageDialog(null, "Invalid Credentials");
            }
            else{
                JOptionPane.showMessageDialog(null, "Account Match");
                
                Dashboard dashboard = new Dashboard ();
                dashboard.setVisible(true);
                dashboard.pack();
                dashboard.setLocationRelativeTo(null);
                this.dispose();
                  
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_logLoginActionPerformed

    private void logEye_InvisibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logEye_InvisibleMouseClicked
        // TODO add your handling code here:
        
        logPassword.setEchoChar((char)0);
        logEye_Invisible.setVisible(false);
        logEye_Visible.setVisible(true);
    }//GEN-LAST:event_logEye_InvisibleMouseClicked

    private void logEye_VisibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logEye_VisibleMouseClicked
        // TODO add your handling code here:
        
        logPassword.setEchoChar('*');
        logEye_Invisible.setVisible(true);
        logEye_Visible.setVisible(false);
    }//GEN-LAST:event_logEye_VisibleMouseClicked

    private void logPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_logPasswordKeyPressed
        // TODO add your handling code here:
                                    
                                    
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        logLoginActionPerformed(null); // Call your existing login function
    }

    

    }//GEN-LAST:event_logPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logEye_Invisible;
    private javax.swing.JLabel logEye_Visible;
    private javax.swing.JButton logLogin;
    private javax.swing.JLabel logLogo;
    private javax.swing.JPasswordField logPassword;
    private javax.swing.JTextField logUsername;
    // End of variables declaration//GEN-END:variables
}
